# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/182WVA9b0zDr5KYrA_Bvj5JwAVm2NoUax
"""

import tweepy
import csv

# Authenticate to Twitter API
consumerKey = 'XWqbYcAioN9622YTSHGgODe0X'
consumerSecret = '8FDyi2cdMNbGDfvOXeCZKy5iw7CcZ2KnbHHXduonpwGDsgtfPd'
accessToken = '1565925882291621888-TvlGhC7yLu1siKu02RMmYhMVMU8vF6'
accessTokenSecret = 'obCyAaINCtdUPGVxAkel8vv75IECKs04kA2SzgiEFNC13'
auth = tweepy.OAuthHandler("consumerKey", "consumerSecret")
auth.set_access_token("accessToken", "accessTokenSecret")

#create  the authentication object
authenticate = tweepy.OAuthHandler(consumerKey , consumerSecret )

#set the access token 
authenticate.set_access_token(accessToken , accessTokenSecret)

#Creating api object
api = tweepy.API(authenticate)

while True:
  keyword = input("Enter the keyword or hashtag to search:")
  noOfTweet = int(input("How many tweets do you want to search:"))

  if keyword == "":
    print("Invalid keyword")
    continue

  tweets = tweepy.Cursor(api.search_tweets , q=keyword).items(noOfTweet)
  tweet_list = []

  for tweet in tweets:
    tweet_list.append(tweet.text)
  break

len(tweet_list)

import pandas as pd

df = pd.DataFrame(tweet_list)
df.to_csv('output1.csv', mode='a', header=False)